# Generated by Django 3.0 on 2020-08-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Course ID')),
                ('name', models.TextField(verbose_name='Course Name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher', verbose_name='Teacher ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Student ID')),
                ('name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('whatsapp', models.BooleanField(verbose_name='Whatsapp Availability')),
                ('mobile', models.BigIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Course Name')),
                ('marks', models.IntegerField(verbose_name='Quiz Marks')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student', verbose_name='Student ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSent',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Quiz Sent ID')),
                ('description', models.TextField(verbose_name='Quiz Description')),
                ('total_marks', models.IntegerField(verbose_name='Total Marks')),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student', verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='QuizReceived',
            fields=[
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.QuizSent', verbose_name='Quiz Sent ID')),
                ('marks', models.IntegerField(verbose_name='Quiz Marks')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student', verbose_name='Student ID')),
            ],
        ),
    ]
