# Generated by Django 3.0 on 2020-08-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Sent Time')),
                ('description', models.TextField(verbose_name='Description')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReceiver',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Received Time')),
                ('description', models.TextField(verbose_name='Description')),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student', verbose_name='Mobile Number')),
            ],
        ),
    ]
