<<<<<<< HEAD
# Generated by Django 3.0 on 2020-08-16 09:50
=======
# Generated by Django 3.0 on 2020-08-16 08:54
>>>>>>> 4b96d6eaa81a6d5fc60e1f77ed6822ba4ee701bd

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneno', models.BigIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
            ],
        ),
    ]
